from __future__ import annotations

from pathlib import Path
from xml.sax.saxutils import escape
import zipfile


BASE_DIR = Path(__file__).resolve().parent


GDD_LINES = [
    "# GDD - Matetic",
    "",
    "## Visao",
    "Matetic e um jogo de matematica online para web, Android e iOS, com partidas rapidas, progressao em mapa de niveis, score, timer, modos variados e dificuldade crescente. A experiencia deve combinar a clareza de um app educacional com a retencao e progressao de um puzzle casual.",
    "",
    "## Objetivo do produto",
    "- Tornar treino matematico divertido, competitivo e rejogavel.",
    "- Oferecer sessoes curtas de 1 a 5 minutos.",
    "- Premiar velocidade, precisao e consistencia.",
    "- Criar loop de progressao com fases, niveis, estrelas, ligas e eventos.",
    "",
    "## Publico-alvo",
    "- Criancas e adolescentes em fase escolar.",
    "- Jovens e adultos que querem praticar calculo mental.",
    "- Usuarios casuais mobile que gostam de progressao estilo saga.",
    "- Professores ou pais que queiram recomendar treino leve e continuo.",
    "",
    "## Plataformas",
    "- Web",
    "- Android",
    "- iOS",
    "",
    "## Pilares do jogo",
    "- Acessivel: entender e jogar em segundos.",
    "- Progressivo: a dificuldade cresce de forma perceptivel.",
    "- Competitivo: score, ranking e duelo online.",
    "- Recompensador: XP, estrelas, desbloqueios e metas.",
    "- Confiavel: partidas rapidas, poucos cliques, feedback imediato.",
    "",
    "## Core loop",
    "- Usuario escolhe fase ou modo.",
    "- Partida comeca com objetivo e tempo.",
    "- Jogador responde desafios matematicos.",
    "- Acertos aumentam score, combo e progresso.",
    "- Erros quebram combo e podem consumir tempo ou vida.",
    "- Ao final, recebe estrelas, XP, moedas e progresso.",
    "- Novas fases, temas e modos sao desbloqueados.",
    "",
    "## Loop de retencao",
    "- Entrar diariamente.",
    "- Coletar recompensa diaria.",
    "- Cumprir missao do dia.",
    "- Jogar fases novas ou rejogar para melhorar estrelas.",
    "- Subir no ranking semanal.",
    "- Desbloquear recompensas cosmeticas e funcionais.",
    "",
    "## Fantasia do jogador",
    "- Estou ficando mais rapido e inteligente.",
    "- Estou vencendo fases dificeis.",
    "- Meu perfil mostra minha evolucao.",
    "- Consigo competir com outras pessoas.",
    "- Cada sessao curta vale a pena.",
    "",
    "## Genero",
    "- Puzzle casual.",
    "- Quiz de matematica.",
    "- Progressao por fases.",
    "- Multiplayer competitivo opcional.",
    "",
    "## Sessao ideal",
    "- 1 a 3 minutos por fase.",
    "- 5 a 10 minutos por sessao casual.",
    "- 15 a 25 minutos por sessao de progressao intensa.",
    "",
    "## Moeda e progressao",
    "- XP: sobe nivel da conta.",
    "- Estrelas: desbloqueiam caminho no mapa.",
    "- Moedas: compram temas, avatares e boosters.",
    "- Liga: posicao competitiva semanal.",
    "- Capitulos: agrupam mundos ou conjuntos de fases.",
    "",
    "## Progressao do jogador",
    "- Nivel da conta sobe por XP.",
    "- Fases liberam caminho no mapa.",
    "- Cada fase pode dar 1 a 3 estrelas.",
    "- Capitulos posteriores introduzem novos tipos de desafio.",
    "- Dificuldade aumenta por operacao, velocidade e pressao.",
    "",
    "## Progressao de dificuldade",
    "- Numeros pequenos para grandes.",
    "- Uma operacao para multiplas operacoes.",
    "- Alternativas faceis para alternativas proximas.",
    "- Mais tempo para menos tempo.",
    "- Menos distracao para mais pressao visual.",
    "- Perguntas diretas para problemas interpretativos.",
    "- Fases com penalidades especiais.",
    "- Objetivos compostos, como 10 acertos seguidos.",
    "",
    "## Tipos de conteudo matematico",
    "- Soma.",
    "- Subtracao.",
    "- Multiplicacao.",
    "- Divisao.",
    "- Comparacao de valores.",
    "- Sequencias numericas.",
    "- Fracoes.",
    "- Porcentagem.",
    "- Regra de tres.",
    "- Potencia e raiz.",
    "- Equacoes simples.",
    "- Logica matematica leve.",
    "",
    "## Estrutura de mundos",
    "- Mundo 1: operacoes basicas.",
    "- Mundo 2: velocidade e precisao.",
    "- Mundo 3: multiplicacao e divisao.",
    "- Mundo 4: fracoes e equivalencia.",
    "- Mundo 5: porcentagem e proporcao.",
    "- Mundo 6: expressoes e operacoes combinadas.",
    "- Mundo 7: logica e desafio avancado.",
    "- Mundo 8+: temporadas e eventos.",
    "",
    "## Objetivos de fase",
    "- Atingir score minimo.",
    "- Acertar X questoes.",
    "- Manter combo por Y segundos.",
    "- Sobreviver ate o tempo acabar.",
    "- Vencer um chefe com multiplas etapas.",
    "- Errar no maximo N vezes.",
    "",
    "## Mecanicas principais",
    "- Score: baseado em acerto, velocidade e combo.",
    "- Timer: limite da partida ou contador regressivo.",
    "- Combo: acertos seguidos aumentam multiplicador.",
    "- Streak: sequencia total sem erro.",
    "- Power-ups: congelar tempo, dica, eliminar alternativas, segunda chance.",
    "- Vidas opcional: para mapa estilo saga.",
    "- Boosters pre-partida: consumidos antes de entrar na fase.",
    "",
    "## Mecanicas online",
    "- Ranking global.",
    "- Ranking semanal.",
    "- Ranking por amigos.",
    "- Desafio assincrono: bater score de outro jogador.",
    "- Duelo em tempo real 1v1.",
    "- Torneios temporarios.",
    "- Eventos sazonais.",
    "",
    "## Modos de jogo",
    "- Mapa: campanha principal por fases.",
    "- Classico: fase padrao com meta de score.",
    "- Contra o tempo: maximizar score em tempo fixo.",
    "- Sobrevivencia: termina por erro ou por vidas zeradas.",
    "- Combo Rush: foco em streak alta.",
    "- Duelo: dois jogadores recebem o mesmo conjunto de perguntas.",
    "- Arena: serie curta de partidas ranqueadas.",
    "- Evento: regras especiais por tempo limitado.",
    "",
    "## Condicoes de vitoria e derrota",
    "- Vitoria: atingir meta da fase.",
    "- Derrota: tempo zerado, vidas zeradas ou score insuficiente.",
    "- No duelo: vence quem tiver maior score no mesmo conjunto de desafios.",
    "",
    "## Recompensas",
    "- Estrelas.",
    "- XP.",
    "- Moedas.",
    "- Baus.",
    "- Cosmeticos.",
    "- Titulos ou molduras.",
    "- Progresso em passe de temporada.",
    "",
    "## Economia",
    "- Moedas ganhas em fase, missao e evento.",
    "- Cosmeticos compraveis com moedas.",
    "- Boosters podem custar moedas ou ser dados por recompensa.",
    "- Monetizacao futura pode ser cosmetica e convenience, nao pay-to-win.",
    "",
    "## Missoes",
    "- Diaria: completar 3 fases.",
    "- Diaria: manter combo de 8.",
    "- Semanal: ganhar 20 estrelas.",
    "- Semanal: jogar 10 duelos.",
    "- Missao tematica: resolver 30 questoes de fracao.",
    "",
    "## Personalizacao",
    "- Avatar.",
    "- Moldura de perfil.",
    "- Tema visual.",
    "- Trilha sonora.",
    "- Efeitos de acerto.",
    "- Mascote.",
    "",
    "## Feedback audiovisual",
    "- Acerto com som e animacao curta.",
    "- Erro com feedback claro, mas nao punitivo demais.",
    "- Combo com efeitos crescentes.",
    "- Boss phase com trilha mais intensa.",
    "- Resultado com destaque de melhora pessoal.",
    "",
    "## UX desejada",
    "- Entrar em uma fase em ate 3 toques.",
    "- Leitura simples e fonte grande.",
    "- Botoes grandes para mobile.",
    "- Baixa friccao entre uma partida e outra.",
    "- Feedback imediato e facil de entender.",
    "",
    "## Acessibilidade",
    "- Alto contraste.",
    "- Opcao sem som.",
    "- Reducao de animacoes.",
    "- Suporte a leitor em elementos principais.",
    "- Tamanho de fonte configuravel.",
    "- Distincao visual alem de cor.",
    "",
    "## KPIs",
    "- Retencao D1, D7, D30.",
    "- Media de partidas por sessao.",
    "- Tempo medio por sessao.",
    "- Taxa de conclusao de fase.",
    "- Taxa de falha por capitulo.",
    "- Conversao para duelo online.",
    "- Taxa de retorno por missao diaria.",
    "",
    "## Riscos",
    "- Dificuldade mal calibrada.",
    "- Excesso de complexidade cedo.",
    "- Matchmaking vazio no online.",
    "- Cheat em score e ranking.",
    "- UX lenta no mobile.",
    "- Conteudo repetitivo.",
    "",
    "## Estrategia de lancamento",
    "- Lancar primeiro com campanha, ranking e missoes.",
    "- Ativar duelo real em segunda fase.",
    "- Abrir eventos sazonais depois de retencao estabilizada.",
]


MAPA_TELAS_LINES = [
    "# Mapa de Telas - Matetic",
    "",
    "## Fluxo principal",
    "- Splash.",
    "- Onboarding.",
    "- Login / Cadastro / Visitante.",
    "- Home.",
    "- Mapa de niveis.",
    "- Pre-partida.",
    "- Partida.",
    "- Resultado.",
    "- Volta para mapa ou proxima fase.",
    "",
    "## Telas obrigatorias",
    "### Splash",
    "- Logo.",
    "- Animacao curta.",
    "- Checagem de sessao.",
    "- Preload de assets minimos.",
    "",
    "### Onboarding",
    "- Proposta do jogo.",
    "- Escolha rapida de faixa ou dificuldade inicial.",
    "",
    "### Login",
    "- Google.",
    "- Apple.",
    "- E-mail.",
    "- Visitante.",
    "",
    "### Home",
    "- Botao jogar.",
    "- Progresso geral.",
    "- Ranking resumido.",
    "- Missoes diarias.",
    "- Evento ativo.",
    "- Atalhos para perfil, loja e modos.",
    "",
    "### Mapa de niveis",
    "- Capitulos.",
    "- Fases bloqueadas e desbloqueadas.",
    "- Estrelas obtidas.",
    "- Boss nodes.",
    "",
    "### Selecao de modo",
    "- Campanha.",
    "- Contra o tempo.",
    "- Sobrevivencia.",
    "- Duelo.",
    "- Evento.",
    "",
    "### Pre-partida",
    "- Objetivo da fase.",
    "- Dificuldade.",
    "- Boosters.",
    "- Recompensa estimada.",
    "",
    "### Partida",
    "- Enunciado.",
    "- Opcoes ou teclado.",
    "- Score.",
    "- Timer.",
    "- Combo.",
    "- Progresso do objetivo.",
    "- Pause.",
    "",
    "### Pausa",
    "- Continuar.",
    "- Reiniciar.",
    "- Sair.",
    "",
    "### Resultado",
    "- Score final.",
    "- Acertos e erros.",
    "- Combo maximo.",
    "- XP.",
    "- Moedas.",
    "- Estrelas.",
    "- Botao proxima fase.",
    "",
    "### Perfil",
    "- Avatar.",
    "- Nivel.",
    "- Estatisticas.",
    "- Historico.",
    "- Conquistas.",
    "",
    "### Ranking",
    "- Global.",
    "- Semanal.",
    "- Amigos.",
    "- Por modo.",
    "",
    "### Missoes",
    "- Diarias.",
    "- Semanais.",
    "- Passe.",
    "",
    "### Loja",
    "- Cosmeticos.",
    "- Boosters.",
    "- Temas.",
    "",
    "### Amigos",
    "- Adicionar.",
    "- Convidar.",
    "- Desafiar.",
    "",
    "### Duelo / Matchmaking",
    "- Buscando partida.",
    "- Sala.",
    "- Confronto.",
    "- Resultado PvP.",
    "",
    "### Eventos",
    "- Calendario.",
    "- Regras.",
    "- Recompensas.",
    "",
    "### Configuracoes",
    "- Audio.",
    "- Idioma.",
    "- Notificacoes.",
    "- Acessibilidade.",
    "- Conta.",
]


ARQUITETURA_LINES = [
    "# Arquitetura Tecnica - Matetic",
    "",
    "## Frontend",
    "- Flutter.",
    "- Um codigo para web, Android e iOS.",
    "- Boa performance para UI casual com animacoes.",
    "- Produtividade alta para app/game hibrido.",
    "",
    "## Backend inicial recomendado",
    "- Firebase.",
    "- Firebase Auth.",
    "- Cloud Firestore.",
    "- Firebase Realtime Database ou WebSocket server.",
    "- Cloud Functions.",
    "- Firebase Storage.",
    "- Crashlytics.",
    "- Analytics.",
    "- Remote Config.",
    "",
    "## Alternativa",
    "- Supabase para auth, banco e realtime.",
    "- Edge Functions ou backend proprio para logica competitiva.",
    "",
    "## Arquitetura de cliente",
    "### Presentation",
    "- Telas.",
    "- Widgets.",
    "- Navegacao.",
    "",
    "### Application",
    "- Casos de uso.",
    "- Regras de sessao.",
    "- Progressao.",
    "- Montagem de partidas.",
    "",
    "### Domain",
    "- Entidades.",
    "- Score.",
    "- Fase.",
    "- Jogador.",
    "- Missao.",
    "- Ranking.",
    "",
    "### Data",
    "- Repositorios.",
    "- DTOs.",
    "- APIs.",
    "- Cache local.",
    "",
    "## Gerencia de estado",
    "- Riverpod ou Bloc.",
    "- Recomendacao: Riverpod pela simplicidade e escalabilidade.",
    "",
    "## Persistencia local",
    "- Hive ou Isar para cache local.",
    "- shared_preferences para flags simples.",
    "",
    "## Tempo real",
    "- Realtime Database para MVP de duelo simples.",
    "- Ou backend WebSocket dedicado se quiser escalar PvP melhor.",
    "",
    "## Entidades principais",
    "- User.",
    "- Profile.",
    "- LevelNode.",
    "- Chapter.",
    "- Question.",
    "- Match.",
    "- MatchRound.",
    "- ScoreEntry.",
    "- Mission.",
    "- Reward.",
    "- Inventory.",
    "- Season.",
    "- Leaderboard.",
    "",
    "## Modelo de dados minimo",
    "- users/{userId}",
    "- profiles/{userId}",
    "- progress/{userId}",
    "- chapters/{chapterId}",
    "- levels/{levelId}",
    "- question_sets/{setId}",
    "- matches/{matchId}",
    "- leaderboards/{seasonId}",
    "- missions/daily",
    "- missions/weekly",
    "",
    "## Logica de score",
    "- Score base por acerto.",
    "- Bonus por velocidade.",
    "- Multiplicador por combo.",
    "- Bonus por fase sem erro.",
    "- Penalidade por erro ou por dica usada.",
    "- Calculo final validado no backend em modos competitivos.",
    "",
    "## Anti-cheat",
    "- Score ranqueado calculado no servidor.",
    "- Seeds de partida geradas no backend.",
    "- Logs de eventos por partida.",
    "- Limites de tempo plausiveis.",
    "- Bloqueio de payload inconsistente.",
    "",
    "## Conteudo das fases",
    "- Pode ser gerado por templates.",
    "- Ou pode vir de bancos pre-curados.",
    "- Ideal: fases autorais no comeco e geracao parametrizada depois.",
    "- Parametros: operacao, faixa numerica, tempo, tipo de resposta, armadilhas validas.",
    "",
    "## Estrutura de perguntas",
    "- id.",
    "- difficulty.",
    "- topic.",
    "- subtopic.",
    "- prompt.",
    "- correctAnswer.",
    "- choices.",
    "- explanation.",
    "- timeLimit.",
    "- tags.",
    "",
    "## Modos online",
    "- Assincrono: compara score depois.",
    "- Tempo real: matchmaking, sala, seed comum e sincronizacao de estado.",
    "- Recomendacao: lancar assincrono primeiro e depois 1v1 em tempo real.",
    "",
    "## Niveis e capitulos",
    "- Capitulos configurados por JSON ou Firestore.",
    "- Cada fase define objetivo, dificuldade, reward, unlock condition, hazards e boosters allowed.",
    "",
    "## Remote Config",
    "- Tempo base das fases.",
    "- Curva de dificuldade.",
    "- Valores de recompensa.",
    "- Eventos ativos.",
    "- Balanceamento sem precisar republicar app.",
    "",
    "## Observabilidade",
    "- level_started.",
    "- level_failed.",
    "- level_completed.",
    "- powerup_used.",
    "- duel_started.",
    "- duel_finished.",
    "- mission_claimed.",
    "- crash.",
    "- latencia.",
    "- desconexao em duelo.",
    "",
    "## Pipeline de desenvolvimento",
    "- Flutter + Dart.",
    "- Ambientes: dev, staging e prod.",
    "- CI: analyze, test, build web e build mobile quando necessario.",
    "",
    "## MVP tecnico",
    "- Flutter.",
    "- Firebase Auth.",
    "- Firestore.",
    "- Cloud Functions.",
    "- Leaderboard simples.",
    "- Campanha.",
    "- Score.",
    "- Timer.",
    "- Progressao.",
    "- Perfil.",
    "- Missoes.",
    "",
    "## Roadmap tecnico",
    "### MVP",
    "- Campanha.",
    "- Login.",
    "- Perfil.",
    "- Score.",
    "- Ranking semanal.",
    "- Missoes diarias.",
    "",
    "### V1.5",
    "- Loja.",
    "- Cosmeticos.",
    "- Boosters.",
    "- Analytics robusto.",
    "",
    "### V2",
    "- Desafios entre amigos.",
    "- Duelo assincrono.",
    "- Eventos.",
    "",
    "### V3",
    "- Tempo real.",
    "- Temporadas.",
    "- Clas.",
    "- Torneios.",
]

ROADMAP_LINES = [
    "# Roadmap de Sprints - Matetic",
    "",
    "## Visao do roadmap",
    "O desenvolvimento deve priorizar primeiro o loop jogavel, depois progressao, depois online competitivo e, por fim, camadas de retencao e live ops.",
    "",
    "## Sprint 0 - Preparacao",
    "- Criar repositorio e padrao de branches.",
    "- Configurar Flutter com ambientes dev, staging e prod.",
    "- Definir design tokens, navegacao e estrutura base.",
    "- Integrar Firebase Auth, Firestore, Crashlytics e Analytics.",
    "- Preparar CI com analyze, test e build web.",
    "",
    "## Sprint 1 - Fundacao do jogo",
    "- Splash.",
    "- Login e modo visitante.",
    "- Home inicial.",
    "- Perfil basico.",
    "- Estrutura de pergunta, score e timer.",
    "- Tela de partida funcional com perguntas mockadas.",
    "- Resultado simples.",
    "",
    "## Sprint 2 - Campanha MVP",
    "- Mapa de niveis inicial.",
    "- Fases com desbloqueio sequencial.",
    "- Estrelas por fase.",
    "- XP da conta.",
    "- Persistencia local e remota do progresso.",
    "- Missoes diarias basicas.",
    "",
    "## Sprint 3 - Conteudo e balanceamento",
    "- Banco inicial de perguntas por topico.",
    "- Curva de dificuldade por capitulo.",
    "- Ajuste de tempo por fase.",
    "- Introducao de combo e multiplicador.",
    "- Primeiros power-ups.",
    "",
    "## Sprint 4 - Social e ranking",
    "- Ranking global e semanal.",
    "- Ranking por amigos.",
    "- Historico de score.",
    "- Perfil com estatisticas.",
    "- Desafio assincrono entre jogadores.",
    "",
    "## Sprint 5 - Economia e retencao",
    "- Moedas e recompensas.",
    "- Loja cosmetica.",
    "- Recompensa diaria.",
    "- Missao semanal.",
    "- Passe simples de temporada.",
    "",
    "## Sprint 6 - Online em tempo real",
    "- Matchmaking basico.",
    "- Duelo 1v1 com mesma seed de perguntas.",
    "- Sincronizacao de score e tempo.",
    "- Resultado PvP.",
    "- Regras anti-cheat iniciais.",
    "",
    "## Sprint 7 - Eventos e live ops",
    "- Eventos tematicos.",
    "- Capitulos sazonais.",
    "- Desafios por tempo limitado.",
    "- Remote Config para balanceamento rapido.",
    "",
    "## Sprint 8 - Polimento e lancamento",
    "- Ajustes de UX mobile.",
    "- Melhorias de acessibilidade.",
    "- Otimizacao de performance.",
    "- Revisao de analytics e funil.",
    "- Build final para web, Android e iOS.",
    "",
    "## Entregas por marco",
    "- Marco 1: loop jogavel offline.",
    "- Marco 2: campanha com progresso e missoes.",
    "- Marco 3: ranking e economia.",
    "- Marco 4: duelo online.",
    "- Marco 5: eventos e publicacao.",
]

BANCO_LINES = [
    "# Modelo de Banco - Matetic",
    "",
    "## Abordagem recomendada",
    "Usar Firebase com Auth, Firestore, Cloud Functions e um mecanismo realtime para partidas online.",
    "",
    "## Colecoes principais",
    "- users",
    "- profiles",
    "- progress",
    "- chapters",
    "- levels",
    "- question_sets",
    "- questions",
    "- matches",
    "- leaderboards",
    "- missions",
    "- rewards",
    "- inventory",
    "- seasons",
    "",
    "## users/{userId}",
    "- authProvider",
    "- createdAt",
    "- lastLoginAt",
    "- status",
    "",
    "## profiles/{userId}",
    "- displayName",
    "- avatar",
    "- level",
    "- xp",
    "- coins",
    "- currentLeague",
    "- favoriteMode",
    "",
    "## progress/{userId}",
    "- unlockedChapters",
    "- unlockedLevels",
    "- starsByLevel",
    "- bestScoreByLevel",
    "- lastPlayedLevel",
    "- streakDays",
    "",
    "## chapters/{chapterId}",
    "- order",
    "- title",
    "- theme",
    "- unlockStarsRequired",
    "- bossLevelId",
    "",
    "## levels/{levelId}",
    "- chapterId",
    "- order",
    "- mode",
    "- difficulty",
    "- targetScore",
    "- targetAccuracy",
    "- timeLimitSeconds",
    "- lives",
    "- rewardCoins",
    "- rewardXp",
    "- questionSetId",
    "",
    "## question_sets/{setId}",
    "- topic",
    "- subtopic",
    "- difficultyBand",
    "- selectionRules",
    "- tags",
    "",
    "## questions/{questionId}",
    "- topic",
    "- subtopic",
    "- difficulty",
    "- prompt",
    "- choices",
    "- correctAnswer",
    "- explanation",
    "- timeLimit",
    "- tags",
    "",
    "## matches/{matchId}",
    "- mode",
    "- status",
    "- createdAt",
    "- startedAt",
    "- finishedAt",
    "- playerIds",
    "- seed",
    "- questionOrder",
    "- scores",
    "- winnerId",
    "",
    "## leaderboards/{seasonId}",
    "- type",
    "- startAt",
    "- endAt",
    "- entries",
    "",
    "## missions/{missionId}",
    "- type",
    "- cadence",
    "- objective",
    "- reward",
    "- activeFrom",
    "- activeUntil",
    "",
    "## inventory/{userId}",
    "- boosters",
    "- cosmetics",
    "- unlockedThemes",
    "- ownedAvatars",
    "",
    "## Regras importantes",
    "- Score competitivo deve ser validado no backend.",
    "- Seed de perguntas deve ser gerada no servidor em modos online.",
    "- Progresso de campanha pode ser salvo localmente e sincronizado depois.",
    "- Leaderboards devem ser agregados para leitura rapida.",
]

WIREFRAME_LINES = [
    "# Wireframes Textuais - Matetic",
    "",
    "## Splash",
    "- Logo central.",
    "- Indicador de carregamento.",
    "- Mensagem curta de inicializacao.",
    "",
    "## Login",
    "- Titulo do jogo.",
    "- Botao Google.",
    "- Botao Apple.",
    "- Botao Entrar como visitante.",
    "- Link para politica e termos.",
    "",
    "## Home",
    "- Topo com avatar, nivel, moedas e notificacoes.",
    "- Card principal Jogar agora.",
    "- Card de missao diaria.",
    "- Card de evento ativo.",
    "- Resumo de ranking.",
    "- Barra inferior com Home, Mapa, Ranking, Loja e Perfil.",
    "",
    "## Mapa de niveis",
    "- Fundo tematico por capitulo.",
    "- Trilha de fases em caminho visual.",
    "- Fases concluidas com estrelas.",
    "- Fases bloqueadas com cadeado.",
    "- Boss node ao final do capitulo.",
    "",
    "## Selecao de modo",
    "- Cards de modo com icone, descricao curta e recompensa.",
    "- Campanha.",
    "- Contra o tempo.",
    "- Sobrevivencia.",
    "- Duelo.",
    "- Evento.",
    "",
    "## Pre-partida",
    "- Nome da fase.",
    "- Objetivo.",
    "- Tempo.",
    "- Recompensa.",
    "- Boosters equipaveis.",
    "- Botao iniciar.",
    "",
    "## Partida",
    "- Topo com score, timer e combo.",
    "- Barra de progresso do objetivo.",
    "- Area central com pergunta.",
    "- Respostas em botoes grandes.",
    "- Botao pausa no canto superior.",
    "",
    "## Pausa",
    "- Cartao central com continuar, reiniciar e sair.",
    "",
    "## Resultado",
    "- Score final em destaque.",
    "- Acertos, erros e combo maximo.",
    "- XP e moedas ganhos.",
    "- Estrelas obtidas.",
    "- Botao proxima fase.",
    "- Botao voltar ao mapa.",
    "",
    "## Perfil",
    "- Avatar grande.",
    "- Nome do jogador.",
    "- Nivel e XP.",
    "- Estatisticas gerais.",
    "- Historico recente.",
    "- Conquistas.",
    "",
    "## Ranking",
    "- Abas Global, Semanal e Amigos.",
    "- Lista com posicao, avatar, nome e score.",
    "- Destaque para a posicao do proprio jogador.",
    "",
    "## Loja",
    "- Abas Temas, Avatares, Efeitos e Boosters.",
    "- Cards com preco e preview.",
    "",
    "## Missoes",
    "- Lista de tarefas com progresso visual.",
    "- Recompensa por missao.",
    "- Botao coletar quando concluida.",
    "",
    "## Duelo online",
    "- Tela de busca por oponente.",
    "- Estado da sala.",
    "- Contagem regressiva.",
    "- Partida sincronizada com score espelhado.",
    "- Resultado comparativo final.",
]

BACKLOG_LINES = [
    "# Backlog MVP - Matetic",
    "",
    "## Objetivo do MVP",
    "Entregar uma versao jogavel, divertida e estavel do Matetic com campanha inicial, progresso, score, timer e base para crescimento futuro.",
    "",
    "## Prioridade P0",
    "- Estrutura base do app Flutter.",
    "- Splash e inicializacao.",
    "- Login com visitante e Google.",
    "- Home com CTA Jogar.",
    "- Mapa de niveis inicial.",
    "- Tela de partida funcional.",
    "- Sistema de score.",
    "- Timer por fase.",
    "- Resultado da partida.",
    "- Persistencia de progresso.",
    "- Banco inicial de perguntas.",
    "",
    "## Prioridade P1",
    "- XP da conta.",
    "- Estrelas por fase.",
    "- Desbloqueio de novas fases.",
    "- Perfil basico.",
    "- Ranking semanal.",
    "- Missoes diarias.",
    "- Recompensa diaria.",
    "",
    "## Prioridade P2",
    "- Loja cosmetica simples.",
    "- Boosters basicos.",
    "- Avatares e temas.",
    "- Eventos temporarios simples.",
    "- Ranking entre amigos.",
    "",
    "## Historias de usuario MVP",
    "- Como jogador, quero entrar rapidamente e iniciar uma fase.",
    "- Como jogador, quero receber score por acertos e velocidade.",
    "- Como jogador, quero ver meu progresso no mapa.",
    "- Como jogador, quero desbloquear novas fases ao avancar.",
    "- Como jogador, quero saber meu desempenho ao final da partida.",
    "- Como jogador, quero voltar diariamente para ganhar recompensas.",
    "",
    "## Entregas tecnicas do MVP",
    "- Autenticacao.",
    "- Persistencia de progresso local e remota.",
    "- Estrutura de perguntas e fases.",
    "- Analytics basico.",
    "- Tratamento de erros e logs.",
    "",
    "## Fora do escopo do MVP",
    "- Duelo online em tempo real.",
    "- Clans.",
    "- Torneios complexos.",
    "- Passe premium completo.",
    "- Economia sofisticada.",
]

MONETIZACAO_LINES = [
    "# Monetizacao e Economia - Matetic",
    "",
    "## Principios",
    "- Nao ser pay-to-win.",
    "- Recompensar consistencia e habilidade.",
    "- Monetizacao focada em conveniencia e cosmeticos.",
    "- Preservar experiencia justa em ranking e duelo.",
    "",
    "## Moedas e recursos",
    "- XP: sobe nivel da conta.",
    "- Estrelas: desbloqueiam progresso no mapa.",
    "- Moedas: usadas em loja e boosters.",
    "- Tickets de evento: acesso a modos especiais.",
    "",
    "## Fontes de ganho",
    "- Vitoria em fases.",
    "- Melhor score pessoal.",
    "- Missoes diarias e semanais.",
    "- Recompensa diaria.",
    "- Eventos sazonais.",
    "- Passe de temporada.",
    "",
    "## Itens compraveis",
    "- Avatares.",
    "- Molduras.",
    "- Temas de interface.",
    "- Efeitos visuais e sonoros.",
    "- Boosters limitados para modos solo.",
    "",
    "## Tipos de monetizacao futura",
    "- Remocao de anuncios, se houver anuncios leves.",
    "- Pacotes cosmeticos.",
    "- Passe de temporada premium.",
    "- Pacotes de moedas.",
    "- Ofertas especiais de evento.",
    "",
    "## Boosters permitidos",
    "- Congelar tempo.",
    "- Eliminar duas alternativas.",
    "- Segunda chance.",
    "- Dica visual.",
    "",
    "## Regras de equilibrio",
    "- Boosters nao entram em ranking competitivo sem restricao.",
    "- Modos ranqueados devem ter regras justas e previsiveis.",
    "- Itens pagos nao devem garantir vitoria automatica.",
    "",
    "## Retencao ligada a economia",
    "- Recompensa diaria crescente.",
    "- Missoes com moedas e itens.",
    "- Baus por streak.",
    "- Passe de temporada com trilha gratis e premium.",
]

REGRAS_LINES = [
    "# Documento de Regras do Jogo - Matetic",
    "",
    "## Regra central",
    "O jogador deve resolver desafios matematicos dentro do tempo e com o maior score possivel.",
    "",
    "## Estrutura de uma fase",
    "- A fase possui objetivo.",
    "- A fase possui tempo limite.",
    "- A fase usa um conjunto de perguntas.",
    "- A fase pode ter vidas, combo e bonus.",
    "",
    "## Regras de score",
    "- Acerto gera score base.",
    "- Acerto rapido gera bonus.",
    "- Sequencia de acertos aumenta combo.",
    "- Erro quebra combo.",
    "- Dicas e boosters podem reduzir score maximo da fase.",
    "",
    "## Regras de tempo",
    "- Cada fase tem tempo fixo ou dinamico.",
    "- O tempo pode diminuir por erro em alguns modos.",
    "- O tempo pode ser congelado por booster em modos permitidos.",
    "",
    "## Regras de progressao",
    "- O jogador precisa concluir fases para liberar novas.",
    "- Estrelas representam qualidade de desempenho.",
    "- Capitulos podem exigir numero minimo de estrelas.",
    "",
    "## Modos de jogo",
    "### Campanha",
    "- Fases sequenciais.",
    "- Progressao por mapa.",
    "",
    "### Contra o tempo",
    "- Maximizar score dentro do limite.",
    "",
    "### Sobrevivencia",
    "- O jogo termina ao atingir limite de erros ou vidas.",
    "",
    "### Duelo",
    "- Dois jogadores recebem conjunto equivalente de perguntas.",
    "- Vence quem tiver maior score final.",
    "",
    "## Regras de derrota",
    "- Tempo zerado.",
    "- Vidas zeradas.",
    "- Meta minima nao atingida, quando aplicavel.",
    "",
    "## Regras de vitoria",
    "- Atingir score alvo.",
    "- Completar objetivo da fase.",
    "- Superar o oponente no duelo.",
    "",
    "## Regras de ranking",
    "- Score competitivo deve ser validado no backend.",
    "- Partidas invalidas ou incompletas nao entram no ranking.",
    "- Boosters podem ser bloqueados em modos ranqueados.",
    "",
    "## Regras de conteudo",
    "- Cada pergunta deve ter resposta correta valida.",
    "- O nivel de dificuldade deve respeitar a fase.",
    "- Explicacoes podem ser exibidas em modos educativos.",
]


CONTENT_TYPES_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>
"""

PACKAGE_RELS_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>
"""

DOCUMENT_RELS_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>
"""

STYLES_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal">
    <w:name w:val="Normal"/>
    <w:qFormat/>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading1">
    <w:name w:val="heading 1"/>
    <w:basedOn w:val="Normal"/>
    <w:uiPriority w:val="9"/>
    <w:qFormat/>
    <w:rPr>
      <w:b/>
      <w:sz w:val="32"/>
    </w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading2">
    <w:name w:val="heading 2"/>
    <w:basedOn w:val="Normal"/>
    <w:uiPriority w:val="9"/>
    <w:qFormat/>
    <w:rPr>
      <w:b/>
      <w:sz w:val="26"/>
    </w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading3">
    <w:name w:val="heading 3"/>
    <w:basedOn w:val="Normal"/>
    <w:uiPriority w:val="9"/>
    <w:qFormat/>
    <w:rPr>
      <w:b/>
      <w:sz w:val="22"/>
    </w:rPr>
  </w:style>
</w:styles>
"""

CORE_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>{title}</dc:title>
  <dc:creator>Codex</dc:creator>
  <cp:lastModifiedBy>Codex</cp:lastModifiedBy>
</cp:coreProperties>
"""

APP_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>Codex</Application>
</Properties>
"""


def build_paragraph_xml(line: str) -> str:
    if not line:
        return "<w:p/>"

    style = "Normal"
    text = line
    if line.startswith("### "):
        style = "Heading3"
        text = line[4:]
    elif line.startswith("## "):
        style = "Heading2"
        text = line[3:]
    elif line.startswith("# "):
        style = "Heading1"
        text = line[2:]

    text = escape(text)
    preserve = ' xml:space="preserve"' if line.startswith("- ") else ""
    return (
        f'<w:p><w:pPr><w:pStyle w:val="{style}"/></w:pPr>'
        f'<w:r><w:t{preserve}>{text}</w:t></w:r></w:p>'
    )


def build_document_xml(lines: list[str]) -> str:
    paragraphs = "".join(build_paragraph_xml(line) for line in lines)
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 wp14">
  <w:body>
    {paragraphs}
    <w:sectPr>
      <w:pgSz w:w="12240" w:h="15840"/>
      <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="708" w:footer="708" w:gutter="0"/>
    </w:sectPr>
  </w:body>
</w:document>
"""


def write_docx(path: Path, title: str, lines: list[str]) -> None:
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", CONTENT_TYPES_XML)
        archive.writestr("_rels/.rels", PACKAGE_RELS_XML)
        archive.writestr("word/_rels/document.xml.rels", DOCUMENT_RELS_XML)
        archive.writestr("word/styles.xml", STYLES_XML)
        archive.writestr("word/document.xml", build_document_xml(lines))
        archive.writestr("docProps/core.xml", CORE_XML.format(title=escape(title)))
        archive.writestr("docProps/app.xml", APP_XML)


def main() -> None:
    write_docx(BASE_DIR / "GDD_Matetic.docx", "GDD Matetic", GDD_LINES)
    write_docx(BASE_DIR / "Mapa_de_Telas_Matetic.docx", "Mapa de Telas Matetic", MAPA_TELAS_LINES)
    write_docx(BASE_DIR / "Arquitetura_Tecnica_Matetic.docx", "Arquitetura Tecnica Matetic", ARQUITETURA_LINES)
    write_docx(BASE_DIR / "Roadmap_de_Sprints_Matetic.docx", "Roadmap de Sprints Matetic", ROADMAP_LINES)
    write_docx(BASE_DIR / "Modelo_de_Banco_Matetic.docx", "Modelo de Banco Matetic", BANCO_LINES)
    write_docx(BASE_DIR / "Wireframes_Textuais_Matetic.docx", "Wireframes Textuais Matetic", WIREFRAME_LINES)
    write_docx(BASE_DIR / "Backlog_MVP_Matetic.docx", "Backlog MVP Matetic", BACKLOG_LINES)
    write_docx(BASE_DIR / "Monetizacao_e_Economia_Matetic.docx", "Monetizacao e Economia Matetic", MONETIZACAO_LINES)
    write_docx(BASE_DIR / "Documento_de_Regras_do_Jogo_Matetic.docx", "Documento de Regras do Jogo Matetic", REGRAS_LINES)
    print("Arquivos DOCX gerados com sucesso.")


if __name__ == "__main__":
    main()
